x-mongo-uri: &mongo-uri
  MONGO_URI: "mongodb://mongodb:27017"

services:
  stocks1:
    build:
      context: .
      dockerfile: ./StocksService/Dockerfile
    environment:
      <<: *mongo-uri
    ports:
      - "5001:8000"
    expose:
      - "8000"
    depends_on:
      - mongodb
    restart: always

  capital-gains:
    build:
      context: .
      dockerfile: ./CapitalGainsService/Dockerfile
    ports:
      - "5003:8080"
    depends_on:
      - stocks1
    restart: always

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
